import React from 'react';
import { Link } from 'react-router-dom';
import { 
  Database, 
  Stethoscope, 
  ArrowRight, 
  Info,
  ShieldCheck,
  Zap
} from 'lucide-react';

const ScreeningPortal = () => {
  return (
    <div className="max-w-5xl mx-auto space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-display font-bold text-slate-900 tracking-tight">AI Health Screening Center</h1>
        <p className="text-slate-600 text-lg max-w-2xl mx-auto">Select a specialized screening module to evaluate your risk markers based on clinical datasets.</p>
      </div>

      <div className="grid md:grid-cols-2 gap-8">
        {/* Liver Card */}
        <div className="group relative bg-white rounded-3xl border border-slate-200 p-8 shadow-sm hover:shadow-xl hover:border-saffron/20 transition-all duration-300">
           <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity">
              <Database size={100} />
           </div>
           <div className="w-16 h-16 bg-saffron-light/20 text-saffron-deep rounded-2xl flex items-center justify-center mb-8"><Database size={32} /></div>
           <h2 className="text-2xl font-bold text-slate-900 mb-4 tracking-tight">Liver Health Screening</h2>
           <p className="text-slate-600 mb-8 leading-relaxed">Detailed analysis using Indian Liver Patient Dataset (ILPD) parameters including Billirubin, ALT/AST, and proteins to detect early signs of liver dysfunction.</p>
           
           <div className="space-y-3 mb-10">
              <div className="flex items-center gap-3 text-sm font-semibold text-slate-700">
                 <Zap size={18} className="text-saffron" /> Instant Risk Analysis
              </div>
              <div className="flex items-center gap-3 text-sm font-semibold text-slate-700">
                 <ShieldCheck size={18} className="text-saffron" /> Clinical Data Standards
              </div>
           </div>

           <Link to="/patient/screening/liver" className="w-full btn-primary py-4 px-6 rounded-xl flex items-center justify-between group-hover:shadow-saffron/20">
              <span>Start Liver Screening</span>
              <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
           </Link>
        </div>

        {/* Diabetes Card */}
        <div className="group relative bg-white rounded-3xl border border-slate-200 p-8 shadow-sm hover:shadow-xl hover:border-saffron/20 transition-all duration-300">
           <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity">
              <Stethoscope size={100} />
           </div>
           <div className="w-16 h-16 bg-saffron-light/20 text-saffron-deep rounded-2xl flex items-center justify-center mb-8"><Stethoscope size={32} /></div>
           <h2 className="text-2xl font-bold text-slate-900 mb-4 tracking-tight">Diabetes Risk Evaluation</h2>
           <p className="text-slate-600 mb-8 leading-relaxed">Comprehensive evaluation of metabolic history, lifestyle factors, and physiological markers to predict probability of Type-2 Diabetes.</p>
           
           <div className="space-y-3 mb-10">
              <div className="flex items-center gap-3 text-sm font-semibold text-slate-700">
                 <Zap size={18} className="text-saffron" /> Multi-factor Correlation
              </div>
              <div className="flex items-center gap-3 text-sm font-semibold text-slate-700">
                 <ShieldCheck size={18} className="text-saffron" /> Privacy Protected Data
              </div>
           </div>

           <Link to="/patient/screening/diabetes" className="w-full btn-primary py-4 px-6 rounded-xl flex items-center justify-between group-hover:shadow-saffron/20">
              <span>Start Diabetes Screening</span>
              <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
           </Link>
        </div>
      </div>

      <div className="bg-slate-100 rounded-3xl p-8 flex items-start gap-4 border border-slate-200">
         <div className="shrink-0 p-2 bg-white rounded-xl text-slate-400"><Info size={24} /></div>
         <div>
            <h3 className="font-bold text-slate-900 mb-1">Important Privacy Notice</h3>
            <p className="text-slate-600 text-sm leading-relaxed">Screening results are generated by AI models for informational purposes and risk awareness. They do not constitute a clinical diagnosis. All your medical input is encrypted and only accessible by authorized medical personnel.</p>
         </div>
      </div>
    </div>
  );
};

export default ScreeningPortal;
